### ISSUE TITLE
Allow on-the-fly transcoding via ffmpeg

### ISSUE THREAD

**Issue by daltek** [benkaiser/node-music-player#14]
An option to allow transcoding via ffmpeg would greatly increase usability in remote streaming situations.

FLAC files could be transcoded to e.g. medium/lowish-bitrate ${favourite-lossy-codec} and stream on mobiles without insane bandwidth usage.  Although many in the west have unlimited plans, this would be particularly useful in India and other parts of the world where connectivity is comparatively poor.

Subsonic does this on the fly as it uses stdout instead of temporary files with only minimal delay. A similar implementation would make this a fantastic [Subsonic](http://subsonic.org/) killer -- for music at least.

Thanks.

**Comment by benkaiser** [comment]
Closing as this is an enhancement and has been added to trello.
Trying to keep github issues to just bugs and in-progress development.
Trello card for reference: https://trello.com/c/WmudxWuo/53-allow-on-the-fly-transcoding-via-ffmpeg
