### ISSUE TITLE
Minor feature - queue viewing

### ISSUE THREAD

**Issue by DependencyHell** [benkaiser/node-music-player#30]
I would like to work on this feature, displaying the queue list on a side panel. Any advices?

I think I need to work on the player.queue_pool array. Displaying its content and sorting it on 'add_to_queue' updates.

**Comment by benkaiser** [comment]
This was added in https://github.com/benkaiser/node-music-player/commit/4dacbfb66e3e09722324cfc122d58f875e34756a
