### ISSUE TITLE
Minor feature - cross-fade between songs

### ISSUE THREAD

**Issue by DependencyHell** [benkaiser/node-music-player#31]
I'm very interrested in this feature. Do you already have an idea how it will be working?
I'm doing some research and tests.

**Comment by benkaiser** [comment]
Yeah sounds about right regarding rewriting the `nextTrack` function. Let me know how you go with it.

**Comment by benkaiser** [comment]
Closing as this is an enhancement and has been added to trello.
Trying to keep github issues to just bugs and in-progress development.
Trello card for reference: 
https://trello.com/c/Do2otK2L/25-cross-fade-between-songs
