### ISSUE TITLE
Number of connected clients

### ISSUE THREAD

**Issue by mindnuts** [benkaiser/node-music-player#32]
Hi,

Would it be possible to list the IP addresses from which the clients are connected? Would like to host this app on the intranet and would like to limit number of clients to "X" users at one time.

**Comment by benkaiser** [comment]
Closing as this is an enhancement and has been added to trello.
Trying to keep github issues to just bugs and in-progress development.
Trello card for reference: 
https://trello.com/c/C0D4EQSq/54-add-authentication-of-some-sort
