### ISSUE TITLE
Installation failed at Taglib 

### ISSUE THREAD

**Issue by amandogra** [benkaiser/node-music-player#33]
Hi there,
I am unable to install the node-music-player on my system (Mac OS X Yosemite). Whenever I run npm install I get the following.
```
$ npm install

> taglib@0.8.1 install /Users/amandogra/Work/playground/node-music-player/node_modules/taglib
> node-gyp rebuild

/bin/sh: taglib-config: command not found
gyp: Call to 'taglib-config --cflags' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/amandogra/Work/playground/node-music-player/node_modules/taglib
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm ERR! taglib@0.8.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the taglib@0.8.1 install script.
npm ERR! This is most likely a problem with the taglib package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls taglib
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/amandogra/Work/playground/node-music-player
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```
Please help.

Regards,
Aman Dogra
amandogra@gmail.com

**Comment by benkaiser** [comment]
Hi Aman,

First of all, have you read the README and installed the relevant [dependencies](https://github.com/benkaiser/node-music-player#dependencies)? if so can you give me the output of `taglib-config --version`?

**Comment by amandogra** [comment]
Hi Ben,

I guess the issue is with the 'taglib', because it is not getting installed. I have tried to contact the author of taglib but the email address provided does not exist. 
```
ERR! Failed at the taglib@0.8.1 install script.
npm ERR! This is most likely a problem with the taglib package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
```
I tried to execute `npm install taglib-config` but that says:
```
ERR! 404 'taglib-config' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'node-music-player'
```
I am going to find the git repo for that. Do you have link for taglib or taglib-config repos. What is your suggestion here? What am I missing?

Regards,
Aman Dogra

**Comment by amandogra** [comment]
Hi Ben,

I got the solution. So, this is what I did.  
1. Downloaded the Mac binary from http://www.cmake.org/download/ and installed it
2. 'Tools > Installed for the command line Use' from cmake UI
2. Cloned the taglib repo from https://github.com/taglib/taglib.git 
3. Installed taglib by using following commands:
```
cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_RELEASE_TYPE=Release .
make
sudo make install
```
After this when I ran `taglib-config --version` command I got `1.9.1`. This solved my issue of `npm install`

You might know this already but it was a good learning for me today, so I felt like sharing the info. 

Thanks a lot for your help. Time to go and play with the node-music-player. :) yay!

Regards,
Aman Dogra

**Comment by benkaiser** [comment]
I do believe that the xcode dev tools should ship with cmake, and then homebrew has taglib version 1.9.1 in it's repositories. So roughly what you did is the long way around to get taglib on Mac (as compared to what is in the readme) :)

I hope you enjoy the music player, and please let me know what you like about it, and if you plan to contribute in the future :+1:
