### ISSUE TITLE
Cannot easily access detailed info when song title is long

### ISSUE THREAD

**Issue by dideler** [benkaiser/node-music-player#34]
When a song title is short, I can click the `[+]` button next to it to access detailed info. E.g.

![image](https://cloud.githubusercontent.com/assets/497458/6089774/230a50ba-ae60-11e4-8719-6346fbd7909d.png)

But when the title is long enough to get shortened on hover, I can no longer click the `[+]` button. My cursor goes into the `I` text-selection mode. To access the detailed info in these cases, I have to play the song and then hit the `[+]` in the footer where it shows the currently playing song.

**Comment by benkaiser** [comment]
Update from master and you should be able to click the `[+]` buttons now even when the text is too long.

**Comment by dideler** [comment]
Awesome, thanks for the quick fix!

P.S. Before I found this project I was using `python -m SimpleHTTPServer` to serve my music directory. This player is a much nicer solution :)

**Comment by benkaiser** [comment]
No worries :)

I'm sure it is a much better solution :+1:
