### ISSUE TITLE
Not all songs are rendered on mobile

### ISSUE THREAD

**Issue by dideler** [benkaiser/node-music-player#35]
On mobile (in my case, on a Nexus 4 and 10), not all songs are rendered.

Here's an example where only 32 songs are drawn. The rest of the page is blank.
![image](https://cloud.githubusercontent.com/assets/497458/6096584/f2f4ba46-af90-11e4-9dce-d8e0bd316ca6.png)

The number 32 is calculated by this line
```js
this.how_many_drawn = Math.ceil(window.innerHeight / this.individual_height) * 2;
```
and that value is then assigned to `max` in the `renderSong` function.

*Edit*: A temporary fix I'm using is `this.how_many_drawn = player.songs.length;`

**Comment by benkaiser** [comment]
I had a line of code checking if it was on mobile but it didn't work after I made a change a while back, but it is all good now.

Nice to see you digging right into the music player and finding out some things, are you looking to contribute or work on features at all?

**Comment by dideler** [comment]
Thanks for the fix, though another issue popped up. The list is now jittery when I scroll on mobile -- my guess is because songs are being drawn as I scroll. The temporary fix I was using (i.e. draw all songs) didn't have this issue. Do you think drawing all songs would be too expensive with a large library?

> Nice to see you digging right into the music player and finding out some things, are you looking to contribute or work on features at all?

I'll probably submit some more issues or open a PR if the fix is easy. I don't have much JS or frontend experience, but I'll see what I can do. I'll definitely tinker around with it since I'll be using this often.
