### ISSUE TITLE
Installation according to readme fails on armv6 (node-gyp)

### ISSUE THREAD

**Issue by totalrisp** [benkaiser/node-music-player#38]
I followed the instructions on this site. But when doing npm install:

> ws@0.4.32 install /root/node-music-player/node_modules/express.io/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

this is on
Linux stereo 3.12.28+ #709 PREEMPT Mon Sep 8 15:28:00 BST 2014 armv6l GNU/Linux
with node version 0.12.0 and npm 2.5.1.

I'm completely new to NPM so I'm not sure if this is an issue with the code or the setup or what. So, I'm assuming that some module is not properly installed. Starting the app does open a webpage at the address, but the page is corupted some how (there are two clkicable links that do nothing called "node  music player" and "music"

**Comment by benkaiser** [comment]
Okay a few things so we can get to the bottom of this...

Can you give me the full install log? From when you run `npm install` until when it gives you the prompt back again? I can't gather much information from that one line.

Also the fact you are running an ARM processor could be causing the issue, perhaps google the error along with "armv6" or something and see what comes up?

**Comment by benkaiser** [comment]
Another idea is to run `sudo npm install -g node-gyp` and then do an npm install and see if it works.

**Comment by totalrisp** [comment]
Ok. Tried to install node-gyp globally and it does install, after which nothing changes, however.

From log:

50209 info linkStuff nan@1.0.0
50210 verbose linkBins nan@1.0.0
50211 verbose linkMans nan@1.0.0
50212 verbose rebuildBundles nan@1.0.0
50213 info install nan@1.0.0
50214 info postinstall nan@1.0.0
50215 verbose unlock done using /root/.npm/_locks/nan-55cf406a9e9165b0.lock for /root/node-music-player/node_modules/express.io/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/node_modules/nan
50216 verbose about to build /root/node-music-player/node_modules/express.io/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
50217 info build /root/node-music-player/node_modules/express.io/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
50218 verbose linkStuff [ false,
50218 verbose linkStuff   false,
50218 verbose linkStuff   false,
50218 verbose linkStuff   '/root/node-music-player/node_modules/express.io/node_modules/socket.io/node_modules/socket.io-client/node_modules' ]
50219 info linkStuff ws@0.4.32
50220 verbose linkBins ws@0.4.32
50221 verbose link bins [ { wscat: './bin/wscat' },
50221 verbose link bins   '/root/node-music-player/node_modules/express.io/node_modules/socket.io/node_modules/socket.io-client/node_modules/.bin',
50221 verbose link bins   false ]
50222 verbose linkMans ws@0.4.32
50223 verbose rebuildBundles ws@0.4.32
50224 verbose rebuildBundles [ 'commander', 'nan', 'options', 'tinycolor' ]
50225 verbose gentlyRm vacuuming /root/node-music-player/node_modules/express.io/node_modules/socket.io/node_modules/socket.io-client/node_modules/.bin/wscat
50226 info install ws@0.4.32
50227 verbose unsafe-perm in lifecycle false
50228 verbose stack Error: spawn ENOMEM
50228 verbose stack     at exports._errnoException (util.js:746:11)
50228 verbose stack     at ChildProcess.spawn (child_process.js:1155:11)
50228 verbose stack     at exports.spawn (child_process.js:988:9)
50228 verbose stack     at spawn (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:7:13)
50228 verbose stack     at runCmd_ (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:207:14)
50228 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:175:7
50228 verbose stack     at process._tickCallback (node.js:355:11)
50229 verbose cwd /root/node-music-player
50230 error Linux 3.12.28+
50231 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
50232 error node v0.12.0
50233 error npm  v2.5.1
50234 error code ENOMEM
50235 error errno ENOMEM
50236 error syscall spawn
50237 error spawn ENOMEM
50238 error If you need help, you may report this error at:
50238 error     <http://github.com/npm/npm/issues>
50239 verbose exit [ 1, true ]

**Comment by benkaiser** [comment]
Judging by the error:

```
50228 verbose stack Error: spawn ENOMEM
```

I would recommend you follow the suggestions from [this](http://stackoverflow.com/a/27851999)

Is the device a device with low memory? It could be running out of memory... Do you have swap configured correctly?

**Comment by totalrisp** [comment]
aah... yes. that could very well be it. thanks for your help. i going to look into this and report back

**Comment by benkaiser** [comment]
No worries. let me know how you go and we can close this issue if it's simply a low memory issue :+1:

**Comment by totalrisp** [comment]
I forgot that the embedded linux system that I was using came with a OS that has no swap. Enableing swap surpased this issue, but no changes. This time this in log, and the end result looks exactly the same:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose config Skipping project config: /root/.npmrc. (matches userconfig)
5 error install Couldn't read dependencies
6 verbose stack Error: ENOENT, open '/root/package.json'
6 verbose stack     at Error (native)
7 verbose cwd /root
8 error Linux 3.12.28+
9 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
10 error node v0.12.0
11 error npm  v2.5.1
12 error path /root/package.json
13 error code ENOPACKAGEJSON
14 error errno -2
15 error package.json ENOENT, open '/root/package.json'
15 error package.json This is most likely not a problem with npm itself.
15 error package.json npm can't find a package.json file in your current directory.
16 verbose exit [ -2, true ]

**Comment by benkaiser** [comment]
Where did your log go?

Anyway it was in the github notification email... It looks like you tried to run `npm install` from `/root`. When the music player is actually clones to `/root/node-music-player/`. Every time you hit an error and reply can you plese give me a full log, and properly code embed it with [github markdown](https://guides.github.com/features/mastering-markdown/)?

**Comment by totalrisp** [comment]
Sorry I posted a log that I realized was not the correct one, and the deleted it.

**Comment by totalrisp** [comment]
but there is no other log file. I wonder if it only makes a log  when something fails?

**Comment by benkaiser** [comment]
Yeah not a lot file, I'm just talking the output when you run `npm install`. There is only a `npm-debug.log` file output if it fails. So yeah just show me the output of running `npm install`. If that goes through successfully you can run `node app.js` and it should run just fine.

**Comment by totalrisp** [comment]
I don't have an output write now, but I can describe it -  or maybe reproduce it for you later. A clean install outputs the lines in post 1 of this thread:

    ws@0.4.32 install /root/node-music-player/node_modules/express.io/node_module/socket.io             
    /node_modules/socket.io-client/node_modules/ws
    (node-gyp rebuild 2> builderror.log) || (exit 0)

 and then a a tree stucture of the modules. Running the app with the command you give above starts the program and it states that it is listening at 2000. 

    connect.multipart() will be removed in connect 3.0
    visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
    connect.limit() will be removed in connect 3.0 
    Express server listening on port 2000

Accessing the page with a browser works, but the page is unusable. Lookig at the source in the browser looks, it looks ok, but the way it is displayed is not correct. Tried on mobile, MacBook, Old laptop running Debian testing.

**Comment by benkaiser** [comment]
Did you run `grunt` after npm install?

**Comment by totalrisp** [comment]
yes

**Comment by benkaiser** [comment]
Can you give some screenshots?

**Comment by totalrisp** [comment]
Looks like no javascript:

![Image of failure](http://s22.postimg.org/vfdelkjvl/node_failure.png)

**Comment by benkaiser** [comment]
That's what it looks like when grunt hasn't run, make sure you have grunt globally installed with `sudo npm install -g grunt`, then run `grunt` and then restart/start the server with `node app.js`

**Comment by totalrisp** [comment]
You know what? I thought that grunt was installed with grunt-cli and because running grunt caused the machine to do "stuff" and not give an error, I was sure that it was installed. However, it was not, and now that it is the page looks quite different. I'm sorry that I wasted your time like this, and thanks for helping nevertheless.

**Comment by benkaiser** [comment]
No worries. Glad I could help. Be sure to let me know how your experience with node-music-player goes! :+1:

**Comment by totalrisp** [comment]
Yes, the thing is, I don't know where to do that. You don't seem to have a support forum or something like that .

**Comment by benkaiser** [comment]
just adding on to the issue or creating another issue for it. Or on [gitter](https://gitter.im/benkaiser/node-music-player?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**Comment by totalrisp** [comment]
Thanks, I installed this on PiMusicBox (http://www.woutervanwijk.nl/pimusicbox/)(https://github.com/woutervanwijk/Pi-MusicBox). This is a mopidy (https://www.mopidy.com/) server on raspbian running on Raspberry pi. This is also why the swap is off by default (the RPi uses an sd-card as a drive and it is not good in the long run to write on it, as it has a limited amount of read/write operations that can be performed on it). Something like your sofware should come by default with pimusicbox imo.

I don't have the technical competence to understand as much but it might be that there could have been some easier way to install node music player on this operating system, since it apparently uses some kind of application off node. Here I am using an older version of Raspbery pi that comes with a single core 800 mhz processor and the only problem with that is perhaps that scanning the library is a bit slow i you have lots of music. But with newer versions of RPi with more RAM and the quad-core ARM Cortex-A7 maybe would not have any problem? Unless this is I/O-limited (probably is to some extent) but

**Comment by benkaiser** [comment]
I guess pi-musicbox is their own thing and the different online services are just ones they integrate with (BTW their ui looks really nice). And yeah I just guess node music player might be a bit too heavyweight for a pi, I've tried it on one of my first gen ones before and yeah its real slow.

But yeah I'm glad you managed to get it working! :)

**Comment by totalrisp** [comment]
I tried it to see how it would work and what the UI is like. I am going to install it again on the newer version of PI, and if you want I can report to you if it is any quicker/better.

**Comment by benkaiser** [comment]
Yeah sounds good. Cheers! :)
