### ISSUE TITLE
Homepage rendering issue

### ISSUE THREAD

**Issue by SriramP** [benkaiser/node-music-player#39]
![test](https://cloud.githubusercontent.com/assets/6679689/6829673/fb720c82-d33a-11e4-86f8-dce3a7ceb311.png)
I am getting such a screen and then page loading fails to continue.
What might be the issue?

**Comment by benkaiser** [comment]
You didn't install/run grunt.

Run:
```
sudo npm install -g grunt-cli
grunt
```

**Comment by totalrisp** [comment]
dare I suggest that the documentation is not sufficient. in theory your readme links to the grunt page and if you read that all through you will notice this,  but I wouldn't see much harm in actually directly stating all the steps needed.

**Comment by benkaiser** [comment]
I guess I thought if it said it was a dependency then people would go through and install them, but yeah I guess for the node global dependencies at least I should make it clear. Its a bit harder with the system dependencies such as git and node, and the installation process for them varies by OS.

**Comment by SriramP** [comment]
This worked! 
Thanks ben. This is great job.

**Comment by benkaiser** [comment]
No worries! Enjoy the music player.
