### ISSUE TITLE
Not able to play music (linux/gnome 3/pulseaudio).

### ISSUE THREAD

**Issue by totalrisp** [benkaiser/node-music-player#40]
I have one laptop that runs Gnome 3.14 desktop. Neither one of the two browsers installed (firefox, epiphany) can play the music from node-musicplayer, not on a local install, but also not even on the demo. The browsers do, however, play music from youtube or javascript radio apps on the webpages of radiostations. When this happens an audio appears in pulseaudio that can be amplified and directed to many various sinks. However, on Node-musicplayer nothing appears. I am not sure that this is a problem with node, or with the laptop. But given that 1) this is a fairly recent install with no or minimal tweaking and 2) other web-based audio things work might have something to do with how node offers the audio to the browser?

**Comment by benkaiser** [comment]
Its based on the audio formats your browser supports. Firefox only allows mp3 if the system library is installed for decoding it. In chrome it just works, and yeah, so it depends on the file format of your music library and the browser you are using. For a format table, look here: https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats#Browser_compatibility

So your options are:
- use another browser
- convert your whole library to a format your browser supports or
- add a feature to node-music-player for live transcoding (if a file is not in the format needed, convert it on the fly sending it to the browser and the file system)

**Comment by totalrisp** [comment]
OK, now I see why the same version of firefox works out of the box on OSX. The page clearly says that the OS or Hardware can give the support while Firefox itself cannot for patent reasons.

**Comment by benkaiser** [comment]
Yeah, so like I could probably provide some shim that uses flash, but I'd much rather not and do the transcoding option.
