### ISSUE TITLE
[Feature request] Automatically call auto-find info after youtube download

### ISSUE THREAD

**Issue by xtrm0** [benkaiser/node-music-player#41]
It be cool for the downloader to automatically try to get music info instead of just parsing the youtube title.

**Comment by benkaiser** [comment]
Yeah that would be cool, its just difficult because if there is extra information in the youtube video that's not in the iTunes item for it, then it won't find it accurately. 

If you want to submit a pull request, and it works for most cases, then I'll merge it. :+1:

**Comment by RolfKoenders** [comment]
Like @benkaiser is saying, there is no default format for a youtube video so you never know what the artist or the title is. You could go for complete video title as a 'title' and edit them manually after.

Thinking about editing after; maybe we could show some dialog after the download/processing of the youtube video to manually insert the title and artist?

**Comment by ohnx** [comment]
Videos on YouTube have tags telling what song (along with the artist) is in
the video. The Youtube API might give access to that information.

**Comment by benkaiser** [comment]
@ohnx it doesn't appear to. Having just done a quick google search for how to do so, and the best solutions are ones like scrape the page and hope those tags are visible from within your country / that video is popular enough to support them.

I think @RolfKoenders solution sounds nice regarding prompting the user how they would like the information split (a choice between which one should be artist and which should be title).
A higher priority on my list is fixing the iTunes auto-find info. Currently it just picks the first result and assumes that is the right info and updates the inputs, but a nicer, more user-friendly way would be to show a list of options and let the user pick or opt to cancel if none of them are correct (often the case). One of the biggest annoyances for me is when it autofinds the info but it's part of some collection or album that the actual song isn't from (e.g. I want it's original album but it gives me the information and coverart for some compilation album).

**Comment by benkaiser** [comment]
Okay, I'm closing this now, as we can't automatically do this. We do have the user-intervention option of letting them select how to split the title and artist, but otherwise this isn't possible within youtubes API.
