### ISSUE TITLE
Allow to add begin time and endtime tags

### ISSUE THREAD

**Issue by xtrm0** [benkaiser/node-music-player#42]
Allow the user to edit the begin and endtime ID3. To allow to skip pauses between songs

**Comment by benkaiser** [comment]
This would be handy. Are you interested in implementing it?

**Comment by xtrm0** [comment]
Sure. I'll do it as soon as I can

**Comment by benkaiser** [comment]
Still keen on implementing this @xtrm0 ?

**Comment by benkaiser** [comment]
Looks like this isn't officially supported in the id3 standard, see: https://en.wikipedia.org/wiki/ID3#Extended_tag

However I would be happy to have an implementation that just relies on the local node music player database (i.e. will not be saved and used in other music players).

Trello task created, feel free to create a PR when you have a solution, or comment here if you need help on implementation.

https://trello.com/c/KJNKb937/55-add-start-and-end-time-information-to-each-track
