### ISSUE TITLE
can't find http://localhost:2000/static/lib/headjs/head.min.js (no folder static/lib/)

### ISSUE THREAD

**Issue by fhorta** [benkaiser/node-music-player#47]

**Comment by benkaiser** [comment]
Did you run grunt? These are the kinds of things that happen if you don't run grunt...

**Comment by fhorta** [comment]
I just followed the installation guide.

I ran "sudo npm install -g grunt-cli nodemon". Do I have to run anything
more before install and run?

**Comment by benkaiser** [comment]
You shouldn't... What is the output of `grunt`?

**Comment by fhorta** [comment]
Ben, it worked. In this guide it is not clear about running "grunt". Thank
you.

**Comment by benkaiser** [comment]
Woah, crap. Just looked at the README. I could have sworn I had grunt in there, but apparently not.

It's all fixed up now! :)
