### ISSUE TITLE
Drag and Drop functionality

### ISSUE THREAD

**Issue by superfunkminister** [benkaiser/node-music-player#48]
Allow the user to drag songs onto playlists and queue etc...

**Comment by benkaiser** [comment]
Yeah this would be handy. I don't have a lot of time free atm but I'm open to pull requests!

**Comment by benkaiser** [comment]
Closing this on github as it's not a bug.
Feature has been added to the trello board: https://trello.com/c/R07FJX6f/56-drag-and-drop-songs-onto-playlists-queue
