### ISSUE TITLE
Make chrome for android notifications work

### ISSUE THREAD

**Issue by xtrm0** [benkaiser/node-music-player#50]
Follow up of commit 
https://github.com/benkaiser/node-music-player/commit/343a1102641ad7da8a6a9ba86dbbf46c7f958b5c#commitcomment-11603153

**Comment by benkaiser** [comment]
I did a bunch more research again, and it seems notifications on android is geared for push notifications (which isn't what we are aiming for).

As such I am going to close this issue. But re-open it if you find something with the chrome API on android / some way to make this possible.
