### ISSUE TITLE
Firefox on Ubuntu 14.04 getting a warning related to media resources.

### ISSUE THREAD

**Issue by SanatLV** [benkaiser/node-music-player#55]
Hi there, I'm getting this warning when I'm trying to play a song.

`Media resource http://localhost:2000/songs/MUDxcHqIs29LhIdK could not be decoded.`
`All candidate resources failed to load. Media load paused.`

What I'm doing wrong?

**Comment by SanatLV** [comment]
And if I open localhost:2000 (I'm testing your app on my local machine) in my Google Chrome it works properly.

Don't you have any idea what should I do in order to fix this issue on Firefox?
Thanks in advance

**Comment by ohnx** [comment]
If your music is encoded in a proprietary codec (ie, mp3), you'll have to
download those codecs.

**Comment by benkaiser** [comment]
Yep, @ohnx is spot on.

Here is a table of compatibility:
https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats#Browser_compatibility

Closing now as this isn't an issue with node music player.
