### ISSUE TITLE
MD5@1.3.0 deprecated

### ISSUE THREAD

**Issue by azariah001** [benkaiser/node-music-player#56]
Hi just installing the project and got a warning from NPM regarding the deprecated MD5 module with instructions that md5@2.x should be used. Not sure if this a major issue but figured it was worth an issue report. :)

**Comment by ohnx** [comment]
[node-music-player doesn't seem to explicitly rely on md5@1.3.0](https://github.com/benkaiser/node-music-player/blob/master/package.json#L9).
Perhaps it's another package being used that relies on md5@1.3.0?

**Comment by benkaiser** [comment]
We do depend on MD5 actually, but it's with a `*` so any version should be installed. Perhaps can you give us a log from your terminal @azariah001 ?

**Comment by ohnx** [comment]
Aha! We should be using lowercase md5.
