### ISSUE TITLE
Live Audio Streaming

### ISSUE THREAD

**Issue by coeus-abdullahaziz** [benkaiser/node-music-player#57]
Can this project give me facility to play audio tracks on a port and listeners from all over the world can listen same music from there. And also the server must be play 24/7.

**Comment by ohnx** [comment]
Yes it can.
See http://music.kaiserapps.com/
However, everyone can modify your songs (and playlists) so keep that mind
when sharing links to the player.
Also, your server needa to be up 24/7.

**Comment by coeus-abdullahaziz** [comment]
But your link is not working, Like when i play a song. it actually not playing and no sound coming. :(

**Comment by ohnx** [comment]
Strange. What browser are you using?

**Comment by benkaiser** [comment]
@coeus-abdullahaziz @ohnx there was an issue affecting the hosted version. Not sure what it was, but upgrading and clearing the settings seemed to fix it.

**Comment by benkaiser** [comment]
Closing. Reopen if issue persists.

**Comment by mohammadrezaprw** [comment]
Can we have resumable play instead of download all data before playing?
>> player.js>>this.current_track.load();

**Comment by benkaiser** [comment]
@mohammadrezaprw I'm not 100% certain of this (but I can do some testing to find out) but I'm pretty sure that `.load()` is a non-blocking function. And it will start playing before the whole track is loaded.
