### ISSUE TITLE
Change url

### ISSUE THREAD

**Issue by mohammadrezaprw** [benkaiser/node-music-player#67]
How we can share a music to others by url?

**Comment by ohnx** [comment]
You can share a link to the node-music-player server if it's public.

**Comment by mohammadrezaprw** [comment]
I can only share a web address like IP:2000, but i want share any song by a unique url like IP:2000/songs/song1

**Comment by benkaiser** [comment]
Yeah you can do that @mohammadrezaprw , if you bring up the dev tools in chrome, click the "Network" tab then click the song you want to share, you should see the item show up there (one might be the thumbnail, the other the track). You should be able to grab the link to that track (e.g. one on mine is: `http://localhost:2000/songs/akBAiHa1tv2jeqdd`) and then share that link with someone. It will just share the raw stream directly, no pretty page for displaying it or anything (so they can control-s the page and download it).

Attached is a screenshot of the dev tools networking tab on my machine:

![image](https://cloud.githubusercontent.com/assets/608054/10909116/db363574-828a-11e5-9868-2adff55e64db.png)

**Comment by benkaiser** [comment]
Closing this issue for now, let me know if anything still persists and I will re-open.

**Comment by ohnx** [comment]
@benkaiser on Chrome at least, it will show a simple player for the audio.
