### ISSUE TITLE
youtube playlist download fails

### ISSUE THREAD

**Issue by jots** [benkaiser/node-music-player#70]
neat project!
one thing:
click on "fetch new music" -> youtube
enter playlist url.  It gets the first song and then dies:

```
Express server listening on port 2000
https://www.youtube.com/watch?v=4wgrzp1DCs4&list=PLdvAo5zrwY6iqn2DWdRobnbsW_FV9MMwp
Started converting Youtube movie to mp3
finished!
node-music-player/library_functions.js:654
              finalCallback();
TypeError: finalCallback is not a function
    at  node-music-player/library_functions.js:654:15
    at callback (node-music-player/node_modules/nedb/lib/executor.js:30:17)
    at node-music-player/node_modules/nedb/lib/datastore.js:299:12
    at node-music-player/node_modules/nedb/lib/persistence.js:197:12
    at FSReqWrap.oncomplete (fs.js:82:15)

```
any ideas?

**Comment by benkaiser** [comment]
That's not a playlist link.that's  link to a song in a playlist. If you click on the playlist name on YouTube it will open the actual playlist page.

I know it has the list id in the link, but I wanted to avoid downloading massive playlists when people were on a video of a playlist and they only intended to download that single video.

Also apologies, single youtube video downloading was broken. It now works if you update to latest master. Also youtube modified their API, affecting ytdl-core. So you will need to run an npm upgrade to update the dependencies.

Let me know if this still persists.

**Comment by jots** [comment]
I did a git pull and npm upgrade, used the correct playlist url  and it works!
I did have to reload the page to see the new songs after importing the playlist, not sure if that's by design or not.
thanks so much.

**Comment by benkaiser** [comment]
Good to hear!

Yeah for SoundCloud it works (places them in the SoundCloud playlist
without reload). But I haven't polished the YouTube one. Feel free to trace
it and send a PR if you want to add some polish to it :)
